#static fields representing cities

cities:
  - name: New York
    latitude: 40.7128
    longitude: -74.0060
  - name: London
    latitude: 51.5074
    longitude: -0.1278
  - name: Tokyo
    latitude: 35.6895
    longitude: 139.6917
  - name: Berlin
    latitude: 52.5200
    longitude: 13.4050
  - name: Paris
    latitude: 48.8566
    longitude: 2.3522
  - name: Warsaw
    latitude: 52.2297
    longitude: 21.0122
  - name: Bangkok
    latitude: 13.7563
    longitude: 100.5018
  - name: Krakow
    latitude: 50.0647
    longitude: 19.9450
  - name: Mexico City
    latitude: 19.4326
    longitude: -99.1332
  - name: Madrid
    latitude: 40.4168
    longitude: -3.7038
  - name: Moscow
    latitude: 55.7558
    longitude: 37.6176
  - name: Bogota
    latitude: 4.7110
    longitude: -74.0721
  - name: Brussels
    latitude: 50.8503
    longitude: 4.3517
  - name: Jakarta
    latitude: -6.2088
    longitude: 106.8456
  - name: Rome
    latitude: 41.9028
    longitude: 12.4964

api_url: "https://api.openweathermap.org/data/2.5/weather"
api_key: "efcf10a1634d9b78317af789aa2df2d9"
timeout: 30  # in seconds
