Bangkok:
  base: stations
  clouds:
    all: 100
  cod: 200
  coord:
    lat: 13.7563
    lon: 100.5018
  dt: 1731617057
  id: 1608132
  main:
    feels_like: 306.07
    grnd_level: 1007
    humidity: 86
    pressure: 1008
    sea_level: 1008
    temp: 301.1
    temp_max: 301.1
    temp_min: 300.33
  name: Nonthaburi
  sys:
    country: TH
    id: 9235
    sunrise: 1731626275
    sunset: 1731667651
    type: 1
  timezone: 25200
  visibility: 10000
  weather:
  - description: overcast clouds
    icon: 04n
    id: 804
    main: Clouds
  wind:
    deg: 253
    gust: 0.95
    speed: 0.58
Berlin:
  base: stations
  clouds:
    all: 100
  cod: 200
  coord:
    lat: 52.52
    lon: 13.4
  dt: 1731617100
  id: 6545310
  main:
    feels_like: 278.03
    grnd_level: 1018
    humidity: 89
    pressure: 1023
    sea_level: 1023
    temp: 280.62
    temp_max: 281.61
    temp_min: 279.31
  name: Mitte
  sys:
    country: DE
    id: 2009543
    sunrise: 1731565621
    sunset: 1731597297
    type: 2
  timezone: 3600
  visibility: 10000
  weather:
  - description: overcast clouds
    icon: 04n
    id: 804
    main: Clouds
  wind:
    deg: 283
    gust: 5.36
    speed: 4.02
Bogota:
  base: stations
  clouds:
    all: 75
  cod: 200
  coord:
    lat: 4.711
    lon: -74.0721
  dt: 1731617067
  id: 7033249
  main:
    feels_like: 287.21
    grnd_level: 734
    humidity: 100
    pressure: 1013
    sea_level: 1013
    temp: 287.14
    temp_max: 287.14
    temp_min: 286.43
  name: Santa Barbara Central
  rain:
    1h: 0.59
  sys:
    country: CO
    id: 8582
    sunrise: 1731581021
    sunset: 1731623889
    type: 1
  timezone: -18000
  visibility: 4000
  weather:
  - description: moderate rain
    icon: 10d
    id: 501
    main: Rain
  wind:
    deg: 330
    speed: 2.57
Brussels:
  base: stations
  clouds:
    all: 75
  cod: 200
  coord:
    lat: 50.8534
    lon: 4.347
  dt: 1731616907
  id: 3337389
  main:
    feels_like: 282.12
    grnd_level: 1023
    humidity: 90
    pressure: 1030
    sea_level: 1030
    temp: 282.12
    temp_max: 283.06
    temp_min: 281.54
  name: City of Brussels
  sys:
    country: BE
    id: 1227
    sunrise: 1731567434
    sunset: 1731599829
    type: 1
  timezone: 3600
  visibility: 10000
  weather:
  - description: broken clouds
    icon: 04n
    id: 803
    main: Clouds
  wind:
    deg: 0
    speed: 0.51
Jakarta:
  base: stations
  clouds:
    all: 86
  cod: 200
  coord:
    lat: -6.2088
    lon: 106.8456
  dt: 1731617300
  id: 1642911
  main:
    feels_like: 302.46
    grnd_level: 1004
    humidity: 82
    pressure: 1008
    sea_level: 1008
    temp: 299.88
    temp_max: 299.89
    temp_min: 298.12
  name: Jakarta
  sys:
    country: ID
    id: 2033644
    sunrise: 1731623127
    sunset: 1731667753
    type: 2
  timezone: 25200
  visibility: 10000
  weather:
  - description: overcast clouds
    icon: 04n
    id: 804
    main: Clouds
  wind:
    deg: 206
    gust: 0.51
    speed: 0.64
Krakow:
  base: stations
  clouds:
    all: 75
  cod: 200
  coord:
    lat: 50.0647
    lon: 19.945
  dt: 1731617117
  id: 3085041
  main:
    feels_like: 273.99
    grnd_level: 990
    humidity: 89
    pressure: 1021
    sea_level: 1021
    temp: 277.6
    temp_max: 278.21
    temp_min: 277.14
  name: "\u015Ar\xF3dmie\u015Bcie"
  rain:
    1h: 1.15
  sys:
    country: PL
    id: 2074307
    sunrise: 1731563525
    sunset: 1731596250
    type: 2
  timezone: 3600
  visibility: 6000
  weather:
  - description: light intensity drizzle
    icon: 09n
    id: 300
    main: Drizzle
  - description: moderate rain
    icon: 10n
    id: 501
    main: Rain
  wind:
    deg: 250
    speed: 4.63
London:
  base: stations
  clouds:
    all: 100
  cod: 200
  coord:
    lat: 51.5072
    lon: -0.1276
  dt: 1731617257
  id: 2643743
  main:
    feels_like: 281.35
    grnd_level: 1027
    humidity: 77
    pressure: 1032
    sea_level: 1032
    temp: 282.66
    temp_max: 283.37
    temp_min: 281.8
  name: London
  sys:
    country: GB
    id: 2075535
    sunrise: 1731568648
    sunset: 1731600764
    type: 2
  timezone: 0
  visibility: 10000
  weather:
  - description: overcast clouds
    icon: 04n
    id: 804
    main: Clouds
  wind:
    deg: 40
    speed: 2.57
Madrid:
  base: stations
  clouds:
    all: 75
  cod: 200
  coord:
    lat: 40.4168
    lon: -3.7038
  dt: 1731616955
  id: 6544494
  main:
    feels_like: 286.6
    grnd_level: 944
    humidity: 76
    pressure: 1019
    sea_level: 1019
    temp: 287.16
    temp_max: 288.27
    temp_min: 285.68
  name: Madrid City Center
  sys:
    country: ES
    id: 2084029
    sunrise: 1731567613
    sunset: 1731603516
    type: 2
  timezone: 3600
  visibility: 10000
  weather:
  - description: broken clouds
    icon: 04n
    id: 803
    main: Clouds
  wind:
    deg: 116
    gust: 6.71
    speed: 3.58
Mexico City:
  base: stations
  clouds:
    all: 40
  cod: 200
  coord:
    lat: 19.4326
    lon: -99.1332
  dt: 1731617300
  id: 3530597
  main:
    feels_like: 292.08
    grnd_level: 763
    humidity: 34
    pressure: 1013
    sea_level: 1013
    temp: 293.14
    temp_max: 293.74
    temp_min: 293.09
  name: Mexico City
  sys:
    country: MX
    id: 47729
    sunrise: 1731588264
    sunset: 1731628676
    type: 2
  timezone: -21600
  visibility: 10000
  weather:
  - description: scattered clouds
    icon: 03d
    id: 802
    main: Clouds
  wind:
    deg: 340
    speed: 5.14
Moscow:
  base: stations
  clouds:
    all: 100
  cod: 200
  coord:
    lat: 55.7558
    lon: 37.6176
  dt: 1731617066
  id: 524901
  main:
    feels_like: 269.43
    grnd_level: 990
    humidity: 60
    pressure: 1010
    sea_level: 1010
    temp: 273.37
    temp_max: 273.52
    temp_min: 272.64
  name: Moscow
  sys:
    country: RU
    id: 2094500
    sunrise: 1731560602
    sunset: 1731590690
    type: 2
  timezone: 10800
  visibility: 10000
  weather:
  - description: overcast clouds
    icon: 04n
    id: 804
    main: Clouds
  wind:
    deg: 227
    gust: 7.65
    speed: 3.59
New York:
  base: stations
  clouds:
    all: 0
  cod: 200
  coord:
    lat: 40.7127
    lon: -74.006
  dt: 1731617298
  id: 5128581
  main:
    feels_like: 278.25
    grnd_level: 1020
    humidity: 51
    pressure: 1021
    sea_level: 1021
    temp: 280.61
    temp_max: 281.46
    temp_min: 279.52
  name: New York
  sys:
    country: US
    id: 4610
    sunrise: 1731584540
    sunset: 1731620338
    type: 1
  timezone: -18000
  visibility: 10000
  weather:
  - description: clear sky
    icon: 01d
    id: 800
    main: Clear
  wind:
    deg: 50
    speed: 3.6
Paris:
  base: stations
  clouds:
    all: 100
  cod: 200
  coord:
    lat: 48.8647
    lon: 2.349
  dt: 1731616693
  id: 6455259
  main:
    feels_like: 282.81
    grnd_level: 1019
    humidity: 87
    pressure: 1029
    sea_level: 1029
    temp: 283.45
    temp_max: 284.19
    temp_min: 282.1
  name: Paris
  sys:
    country: FR
    id: 2012208
    sunrise: 1731567519
    sunset: 1731600704
    type: 2
  timezone: 3600
  visibility: 10000
  weather:
  - description: overcast clouds
    icon: 04n
    id: 804
    main: Clouds
  wind:
    deg: 20
    speed: 2.57
Rome:
  base: stations
  clouds:
    all: 0
  cod: 200
  coord:
    lat: 41.9028
    lon: 12.4964
  dt: 1731617299
  id: 6545158
  main:
    feels_like: 279.16
    grnd_level: 1008
    humidity: 63
    pressure: 1018
    sea_level: 1018
    temp: 280.82
    temp_max: 281.39
    temp_min: 279.79
  name: Trevi
  sys:
    country: IT
    id: 2037613
    sunrise: 1731563931
    sunset: 1731599421
    type: 2
  timezone: 3600
  visibility: 10000
  weather:
  - description: clear sky
    icon: 01n
    id: 800
    main: Clear
  wind:
    deg: 70
    speed: 2.57
Tokyo:
  base: stations
  clouds:
    all: 75
  cod: 200
  coord:
    lat: 35.6895
    lon: 139.6917
  dt: 1731617265
  id: 1850144
  main:
    feels_like: 287.69
    grnd_level: 1018
    humidity: 89
    pressure: 1019
    sea_level: 1019
    temp: 287.84
    temp_max: 288.94
    temp_min: 286.81
  name: Tokyo
  rain:
    1h: 1.33
  sys:
    country: JP
    id: 268395
    sunrise: 1731619026
    sunset: 1731656086
    type: 2
  timezone: 32400
  visibility: 7000
  weather:
  - description: light intensity shower rain
    icon: 09n
    id: 520
    main: Rain
  wind:
    deg: 350
    speed: 4.12
Warsaw:
  base: stations
  clouds:
    all: 75
  cod: 200
  coord:
    lat: 52.2297
    lon: 21.0122
  dt: 1731617242
  id: 756135
  main:
    feels_like: 273.79
    grnd_level: 1005
    humidity: 94
    pressure: 1017
    sea_level: 1017
    temp: 278.03
    temp_max: 279.01
    temp_min: 277.55
  name: Warsaw
  sys:
    country: PL
    id: 2035775
    sunrise: 1731563726
    sunset: 1731595537
    type: 2
  timezone: 3600
  visibility: 5000
  weather:
  - description: mist
    icon: 50n
    id: 701
    main: Mist
  wind:
    deg: 270
    gust: 0
    speed: 6.26
